#! /usr/bin/env bash

SCRIPTDIR=$(dirname $0)

## For each PID (starting with 21 since I care about seeing the gluon result asap!)
for pid in -5 -4 -3 -2 -1 1 2 3 4 5 21; do
    ## Run comparison calculations for various fixed Q values
    for q in 10 50 100 200 500 1000 2000 5000; do
        $SCRIPTDIR/cmpv5v6 xf_v*_scanx_q${q}_${pid}.dat -o xfacc_q${q}_${pid}.dat &
    done
    wait
    ## Run comparison calculations for various fixed x values
    for x in 1e-08 1e-06 0.0001 0.01 0.1 0.2 0.5 0.8; do
        $SCRIPTDIR/cmpv5v6 xf_v*_scanq_x${x}_${pid}.dat -o xfacc_x${x}_${pid}.dat &
    done
    wait
    ## Plot absolute PDF values and v5/v6 accuracies
    $SCRIPTDIR/plotv5v6 xf_v*_scanx_q*_$pid.dat --type=xf --axis=x --log=x --ylim=0: -o cmpv5v6_xf_scanx_$pid.pdf &
    $SCRIPTDIR/plotv5v6 xf_v*_scanq_x*_$pid.dat --type=xf --axis=q -o cmpv5v6_xf_scanq_$pid.pdf &
    $SCRIPTDIR/plotv5v6 xfacc_q*_$pid.dat --axis=x -o cmpv5v6_xfacc_scanx_$pid.pdf &
    $SCRIPTDIR/plotv5v6 xfacc_x*_$pid.dat --axis=q -o cmpv5v6_xfacc_scanq_$pid.pdf &
    wait
done
