#! /usr/bin/env python

"""\
Usage: %prog <gridv5.dat> <gridv6.dat>

Compare two dumped grids of PDF xf(x,Q) values. The two input files should be in
a format where each line has three numerical values separated by whitespace,
corresponding to the x, Q2, and xf(x,Q) values sampled. The x and Q values must
be line-by-line identical (within floating point accuracy) between the two data
files. The output files from the migration/testpdf program are the main use case.

Both input data sets are given by lines in the following format:

  x Q xfx

Where xfx is the central value for the top quark given by the set used in v5 and v6.

Program assumes the values produced by v5 are accurate and compares these to values
produced by v6.

Output is given in the following format:

  x Q fractional_accuracy
"""

import optparse, os

op = optparse.OptionParser(usage=__doc__)
op.add_option("-o", dest="OUTPUT", metavar="FILE", help="output file", default="accuracy.dat")
op.add_option("-e", dest="EPSILON", metavar="EPS", help="regulariser in calculation of relative deviations", type=float, default=None)
op.add_option("-t", dest="TOLERANCE", metavar="TOL", help="tolerance scale for accuracy, above which a warning will be written to stdout", type=float, default=0.1)
op.add_option("--as", dest="TYPE", metavar="TYPE", help="alpha_s comparison mode", action="store_const", const="as", default="xf")
op.add_option("-q", dest="VERBOSITY", help="be quiet", action="store_const", const=0, default=1)
op.add_option("-v", dest="VERBOSITY", help="be verbose", action="store_const", const=2, default=1)
opts, args = op.parse_args()

## Use different epsilon regulariser defaults for xf and alpha_s comparisons
if opts.EPSILON is None:
    if opts.TYPE == "xf":
        opts.EPSILON = 0.1
    elif opts.TYPE == "as":
        opts.EPSILON = 0.01

assert len(args) == 2
assert all(os.path.exists(a) for a in args)
#print "Comparing", args[0], args[1]

f5 = open(args[0])
f6 = open(args[1])
out = open(opts.OUTPUT, "w")

def diff(a, b):
    return abs(a-b)
def fracdiff(a, b):
    if a == 0 and b == 0: return 0.0
    return abs(a-b) / max(abs(a), abs(b))
def accuracy(ref, test, epsilon=opts.EPSILON):
    if ref == 0 and test == 0: return 0.0
    ## First defn
    #return abs((test + epsilon) / (ref + epsilon)) - 1.0
    ## Refined defn
    return abs(test - ref) / ( abs(ref) + epsilon )

## Counters for the accuracy thresholds failed (first is an overall counter)
failcounts = { -1 : 0, 1e-3 : 0,  1e-2 : 0, 1e-1 : 0, 1.0 : 0 }

while True:
    l5, l6 = f5.readline(), f6.readline()
    if not l5 or not l6:
        break
    ## PDF value comparisons
    if opts.TYPE == "xf":
        lnx5, lnq5, xf5 = [float(a) for a in l5.split()]
        lnx6, lnq6, xf6 = [float(b) for b in l6.split()]
        assert fracdiff(lnx5, lnx6) < 1e-8 and fracdiff(lnq5, lnq6) < 1e-8
        diff56, acc56 = diff(xf5, xf6), accuracy(xf5, xf6)
        #out.write("%0.3e %0.3e %0.3e\n" % (lnx5, lnq5, diff56))
        out.write("%0.3e %0.3e %0.3e\n" % (lnx5, lnq5, acc56))
        if opts.VERBOSITY == 2 or (opts.VERBOSITY == 1 and acc56 > opts.TOLERANCE):
            print "%0.3e, %0.3e:   %0.3e vs. %0.3e   =   %0.3e, %0.3e   =>   %s" % \
                  (lnx5, lnq5, xf5, xf6, diff56, acc56, "PASS" if acc56 < opts.TOLERANCE else "FAIL")
    ## alpha_s comparisons
    elif opts.TYPE == "as":
        lnq5, as5 = [float(a) for a in l5.split()]
        lnq6, as6 = [float(b) for b in l6.split()]
        assert fracdiff(lnq5, lnq6) < 1e-8
        diff56, acc56 = diff(as5, as6), accuracy(as5, as6)
        out.write("%0.3e %0.3e\n" % (lnq5, acc56))
        if opts.VERBOSITY == 2 or (opts.VERBOSITY == 1 and acc56 > opts.TOLERANCE):
            print "%0.3e:   %0.3e vs. %0.3e   =   %0.3e, %0.3e   =>   %s" % \
                  (lnq5, as5, as6, diff56, acc56, "PASS" if acc56 < opts.TOLERANCE else "FAIL")
    ## Update accuracy threshold failure filters
    for acc_cut in failcounts:
        if acc56 > acc_cut:
            failcounts[acc_cut] += 1

## Print out threshold failure rates
#print failcounts
for acc_cut in sorted(failcounts.keys())[1:]:
    failrate = failcounts[acc_cut] / float(failcounts[-1])
    if failrate:
        print "%0.1f%% of points fail acc < %0.1e cut in print %s vs %s" % (100*failrate, acc_cut, args[0], args[1])
