#! /usr/bin/env python

"""\
Both input data sets are given by lines in the following format:

  x Q2 xfx

Where xfx is the central value for the top quark given by the set used in v5 and v6.

Program assumes the values produced by v5 are accurate and compares these to values
produced by v6 and plots them using gnuplot.

Output is given in the following format:

  x Q2 delta_xfx fractional_accuracy
"""

## Finds the absolute values of the differences between two lists of values
def delta(xs, ys):
    delta = [abs(x - y) for x, y in zip(xs, ys)]
    return delta

## Finds the fractional accuracy of a difference with respect to some assumed correct value
def fractional_accuracy(deltas, xs):
    acc = [(delta / x) for delta, x in zip(deltas, xs)]
    return acc

v5_data = open('dumpv5.txt', 'r')
v6_data = open('dumpv6.txt', 'r')

xs = []
q2s = []
xfxs_5 = []
xfxs_6 = []
delta_xfxs = []
acc = []

for line in v5_data:
    line_string = line.split()
    xs.append(float(line_string[0]))
    q2s.append(float(line_string[1]))
    xfxs_5.append(float(line_string[2]))

for line in v6_data:
    line_string = line.split()
    xfxs_6.append(float(line_string[2]))

delta_xfxs = delta(xfxs_5, xfxs_6)
acc = fractional_accuracy(delta_xfxs, xfxs_5)

with open("accuracy.dat", 'wb') as output:
    for i, data in enumerate(acc):
        print >>output, str(xs[i]) + ' ' + str(q2s[i]) + ' ' + str(delta_xfxs[i]) + ' ' + str(acc[i])
