#! /usr/bin/env python

"""\
Usage: %prog <data1.dat> <data2.dat> [...]

Plot the given PDF comparison files.
"""

import optparse, os

op = optparse.OptionParser(usage=__doc__)
op.add_option("-o", dest="OUTPUT", metavar="FILE", help="output file", default="cmpv5v6.pdf")
op.add_option("--axis", dest="AXIS", metavar="AXIS", help="axes mode: x, q, xq", default="x")
op.add_option("--type", dest="TYPE", metavar="TYPE", help="value type being plotted: xf, fracdiff", default="fracdiff")
op.add_option("--log", dest="LOG", metavar="SCALETYPE", help="axes logarithmic plotting: x, y, xy", default="xy")
op.add_option("-t", dest="TOLERANCE", metavar="TOL", help="acceptable level of fractional deviation", type=float, default=1e-3)
op.add_option("--pdfxmin", dest="PDFXMIN", metavar="X", help="low edge of the PDF range in x", type=float, default=None)
op.add_option("--pdfqmax", dest="PDFQMAX", metavar="Q", help="high edge of the PDF range in Q", type=float, default=None)
op.add_option("--xlim", dest="XLIM", metavar="Xlow:Xhigh", help="edges of the plot range in x, colon-separated", default=None)
op.add_option("--ylim", dest="YLIM", metavar="Ylow:Yhigh", help="edges of the plot range in y, colon-separated", default=None)
op.add_option("--vlines", dest="VLINES", metavar="FILE", help="plot a vertical line at each of the space-separated values in FILE", default=None)
# TODO: PID specification
# TODO: Logx/y and limits control
opts, args = op.parse_args()

assert len(args) > 1
assert all(os.path.exists(a) for a in args)


import matplotlib.pyplot as plt
plt.rcParams["font.family"] = "serif"
# plt.rcParams["font.serif"] = "Computer Modern Roman"
# plt.rcParams["text.usetex"] = True

STYLES = ["-", ":", "--", "-."]
COLORS = ["red", "blue", "darkgreen", "orange", "purple"]
PARTONS = {-5:r"$\bar{b}$",-4:r"$\bar{c}$",-3:r"$\bar{s}$",-2:r"$\bar{u}$",-1:r"$\bar{d}$",
           1:r"$d$",2:r"$u$",3:r"$s$",4:r"$c$",5:r"$b$",21:r"$g$"}

def latex_float(f):
    float_str = "{0:.2g}".format(f)
    if "e" in float_str:
        mant, exp = float_str.split("e")
        exp = int(exp)
        return r"{0} \times 10^{{{1}}}".format(mant, exp)
    else:
        return float_str

## Do correct sorting, and labels as file:label args
index_fname = {}
fname_label = {}
for i, a in enumerate(args):
    index = i
    if ":" in a:
        fname, label = a.split(":", maxsplit=1)
    else:
        fname = a
        label = a.replace(".dat", "").replace("_", " ")
        # try:
        details = label.split()
        if details[1].startswith("v"):
            details[0] += " " + details[1]
            del details[1] # remove v5/6
            del details[1] # remove scanx/q
            #print details
        yvar = details[0]
        xvar = details[1][0]
        xval = float(details[1][1:])
        pid = int(details[2])
        label = r"{yvar}, flav = {flav}, ${xvar} = {xval}$".format(yvar=yvar, xvar=xvar, xval=latex_float(xval), flav=PARTONS.get(pid, pid))
        index = xval
        # except:
        #     pass
    index_fname[index] = fname
    fname_label[fname] = label

## Plot each line
i = 0
for _, fname in sorted(index_fname.iteritems()):
    f = open(fname)
    xs, qs, vals = [], [], []
    for line in f:
        x, q, val = [float(a) for a in line.split()]
        if opts.AXIS == "x":
            xs.append(x)
        elif opts.AXIS == "q":
            xs.append(q)
        else:
            print "xq axis type (2D plotting) not yet supported"
            exit(1)
        vals.append(val)
    # TODO: Line styles and colors (from cmd line? group by v5/v6)
    color = COLORS[i % len(COLORS)]
    style = STYLES[(i / len(COLORS)) % len(COLORS)]
    i += 1
    plt.plot(xs, vals, label=fname_label[fname], linestyle=style, color=color)

## Set up axes with log scales
if "x" in opts.LOG:
    plt.xscale("log")
if "y" in opts.LOG:
    plt.yscale("log")
    if opts.TYPE == "fracdiff":
        plt.ylim(ymin=1e-5)

## Set (override) axis limits
if opts.XLIM:
    xlow, xhigh = opts.XLIM.split(":")
    if xlow: plt.xlim(xmin=float(xlow))
    if xhigh: plt.xlim(xmax=float(xhigh))
if opts.YLIM:
    ylow, yhigh = opts.YLIM.split(":")
    if ylow: plt.ylim(ymin=float(ylow))
    if yhigh: plt.ylim(ymax=float(yhigh))

## Set up axis labels and plot title
if opts.AXIS == "xq":
    ## 2D plotting
    plt.xlabel("$x$")
    plt.ylabel("$Q$")
    # TODO: Implement!
    print "xq axis type (2D plotting) not yet supported"
    exit(1)
else:
    ## 1D plotting
    if opts.TYPE == "xf":
        plt.ylabel("$xf(x,Q)$")
    elif opts.TYPE == "fracdiff":
        # plt.ylabel("$|f_6 - f_5| / |f_5|$")
        plt.ylabel(r"$|f_6+\epsilon|/|f_5+\epsilon| - 1$")
    #
    if opts.AXIS == "x":
        plt.xlabel("$x$")
        if opts.PDFXMIN:
            plt.axvline(opts.PDFXMIN, linewidth=1, color="black", linestyle=":")
    elif opts.AXIS == "q":
        plt.xlabel("$Q$")
        if opts.PDFQMAX:
            plt.axvline(opts.PDFQMAX, linewidth=1, color="black", linestyle=":")

## Plot vertical lines from a file (e.g. for marking all knot values)
if opts.VLINES:
    f = open(opts.VLINES)
    for line in f:
        for xval in [float(x) for x in line.split()]:
            plt.axvline(xval, linewidth=1, color="gray", linestyle=":")

## Legend
l = plt.legend(loc=0, ncol=2, frameon=False)
for t in l.get_texts():
    t.set_size("xx-small")

## If plotting fractional deviations, draw the tolerance level
if opts.TYPE == "fracdiff":
    plt.axhline(opts.TOLERANCE, linewidth=1, color="red", linestyle=":")

## Save the plot
plt.savefig(opts.OUTPUT)
